language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq libgdal1h
install:
  - pip install -r requirements.txt
script:
  - pytest