language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
before_install:
  - sudo apt-get install -qq libgdal1h
  - sudo apt-get install -qq python-numpy python-scientific
  - sudo apt-get install -qq python-shapely
  - sudo apt-get install -qq python-qt4
  - sudo apt-get install -qq proj
  - sudo apt-get install -qq gmsh
  - sudo apt-get install -qq gmt
  - sudo apt-get install -qq python-gdal
  - sudo apt-get install -qq python-cairo
install:
  - pip install -r requirements.txt
script:
  - pytest