language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - gdal-bin
      - netcdf-bin
      #- python-gdal # GDAL from UbuntuGIS results in error for line `from osgeo import ogr`: ModuleNotFoundError: No module named 'osgeo'
before_install:
  - gdal-config --version
  # installation of gdal Python package, see https://stackoverflow.com/a/17311033
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install gdal==`gdal-config --version`
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - pip install -r requirements-dev.txt
script:
  - pytest
 
jobs:
  include:
    - stage: build docs
      python: "3.7"
      if: branch = master AND type != pull_request 
      script:
        - pip install -r docs/requirements-docs.txt
        - pip install -r docs/requirements.txt
        - pip install -e .
        - shopt -s expand_aliases
        - |-
          if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_REPO_SLUG == $GH_SLUG ]]; then
            ./docs/site_build.sh
          fi

env:
  global:
    - GH_USER_NAME: "Opening Reproducible Research"
    - GH_USER_EMAIL: "openingrr@uni-muenster.de"
    - GH_SLUG: "o2r-project/geoextent"
    - secure: "TjE9UQ+FWwUJjJPiVYGztT0kVf99+ZN0FpZOGJuNj1pyycoqRB09T+cPXOzi8nlIcctJe74QxCkrww26bio1P7TMqoeSjGWcAFl+EcgE8p0G75NFwMphzHQ9RXM1MQgmvY5hlhw8hFVh7IEBZQNxX+z5Qhs8lQ13egisLbZ+Prj4qYEEx/Xt6NvYKBXYUBuzTa1NBAmP1ghVjDynYDRdhqLAdBesJ/rTzp9Mdx5ZJgMHmSNuo/wZk9VQuMKx+V4chQdMsM37a+DYRA4WLqAFs01ec09Ava6Vi0qfAuqZ30lVdJnn8BhmTcUmxA4y79AB30xhwJUiqySfzq0eYs9TrxdMr9Kv5Vq7xqxJC2k2c4dip5H1Eo61qjG/qhlCaleDK9GnrYzE7q2v4FhT+ToN6L6H3Lwb5YsEoEhNRWr69sxqFgihlsfcCFchf8WyVQ6tICybu/HIe/1cyCAtgSAaOUfqQBmvx6bYJjhvVkUGqIByEZFrajqniWTM31BlL+Lb8KpNMgteOA4VfpJdwnzgcUQFbXrcbwcIHLNr+5Gb5LUayalC/jE+ln+C6z5NmTzpGst9Y8plV3Lw8GbGFxTYAFe/VJ4VadBrG9i+v6g9AX7KWGZ1lUJgstK6iBzX9B0xb8X60yj57vMT7tOeRZf1MczIyizzXKefeTb7d+cPGMk="
