sudo: false
language: python
python:
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libproj-dev
      - libgeos-dev
      - libspatialite-dev
      - libgdal-dev
      - gdal-bin
      - netcdf-bin
      #- python-gdal # GDAL from UbuntuGIS results in error for line `from osgeo import ogr`: ModuleNotFoundError: No module named 'osgeo'
before_install:
  - gdal-config --version
  # installation of gdal Python package, see https://stackoverflow.com/a/17311033
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - pip install gdal==`gdal-config --version`
install:
  - pip install -r requirements.txt
  - pip install -e .
before_script:
  - pip install -r requirements-dev.txt
script:
  - pytest
#after_script:
#  - TODO code coverage
